apiVersion: v1
kind: Service
metadata:
  name: helloworld-flask
  labels:
    name: helloworld-flask
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32007
  selector:
    name: helloworld-flask
  type: NodePort